[package]
name = "cpe490"
version = "0.1.0"
authors = ["Peter Ho <pho@buhao.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bus = "2.2.3"
crossbeam = "0.8.0"
